version: '3.4'

services:
  kong-ee:
    image: "${KONG_DOCKER_TAG:-kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:latest}"
    command: kong docker-start #sh -c "kong migrations bootstrap && /docker-entrypoint.sh kong docker-start"
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_CASSANDRA_CONTACT_POINTS: ${POSTGRES_HOST:-db}
      KONG_DATABASE: postgres
      KONG_LICENSE_DATA: '${KONG_LICENSE_DATA}'
      KONG_LOG_LEVEL: debug
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kongee}
      KONG_PG_HOST: ${POSTGRES_HOST:-db}
      KONG_PG_PASSWORD: ${POSTGRES_PASSWORD:-kong}
      KONG_PG_SSL: 'on'
      KONG_PG_USER: ${POSTGRES_USER:-kong}
      KONG_PORTAL: 'on'
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_VITALS: 'on'
    ports:
      - "8000:8000/tcp"
      - "8443:8443/tcp"
      - "8001:8001/tcp"
      - "8444:8444/tcp"
      - "8002:8002/tcp"
      - "8445:8445/tcp"
      - "8003:8003/tcp"
      - "8004:8004/tcp"
    restart: on-failure
    stdin_open: true
    tty: true
